// Regenerates migrations/0002_seed.sql from src/seed.ts — catalog metadata ONLY.
// The synthetic health series (uptime90/latency48/p50/p95/healthScore/lastCheckedMin)
// are dev fixtures and never touch D1 (Δ2 honesty gate: real numbers or none).
// status/diedAt/epitaph ARE catalog facts and do export.
// Deterministic: same seed in, byte-identical SQL out — no Date.now(), no randomness.
//
// For ADDING apis to an existing D1 (keeps probe history): use export-catalog-delta.ts instead.
//
// run:  node scripts/export-seed.ts          (Node ≥ 22.18 strips types natively)
//  or:  npx tsx scripts/export-seed.ts

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { endpointUrl } from '../src/data/seed.ts'
import { apis, categories } from '../src/data/seed.ts'

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const opt = (s: string | null | undefined) => (s == null ? 'NULL' : q(s))
const bool = (b: boolean) => (b ? '1' : '0')
// cors is tri-state in the catalog; the column is cors_verified (1/0/null = unverified)
const cors = (c: 'yes' | 'no' | 'unknown') => (c === 'yes' ? '1' : c === 'no' ? '0' : 'NULL')

const catId = new Map(categories.map((c, i) => [c.slug, i + 1]))
const lines: string[] = [
  '-- 0002_seed — generated by scripts/export-seed.ts. Do NOT hand-edit; regenerate instead.',
  '-- Catalog metadata only: synthetic health series never leave src/seed.ts (Δ2).',
  '-- monitored_since is NULL everywhere — it gets stamped by the first REAL check.',
  '',
]

lines.push('-- categories (api_count precomputed from the seed; api_count nightly rollup maintains it after)')
for (const c of categories) {
  const n = apis.filter((a) => a.category === c.slug).length
  lines.push(
    `insert into categories (id, slug, name, emoji, description_md, api_count) values ` +
      `(${catId.get(c.slug)}, ${q(c.slug)}, ${q(c.name)}, ${q(c.emoji)}, ${q(c.blurb)}, ${n});`
  )
}

lines.push('')
lines.push('-- apis — health_score/verified_at/last_checked_at stay NULL until the checker runs')
apis.forEach((a, i) => {
  const id = i + 1
  const cat = catId.get(a.category)
  if (!cat) throw new Error(`unknown category ${a.category} on ${a.slug}`)
  lines.push(
    `insert into apis (id, slug, name, emoji, tagline, description_md, category_id, docs_url, base_url, ` +
      `auth_type, check_tier, https, cors_verified, free_tier_notes, rate_limit_notes, requires_card, commercial_use, ` +
      `data_license, status, added_at, monitored_since, tombstoned_at, epitaph) values ` +
      `(${id}, ${q(a.slug)}, ${q(a.name)}, ${q(a.emoji)}, ${q(a.tagline)}, ${q(a.description)}, ${cat}, ` +
      `${q(a.docsUrl)}, ${q(a.baseUrl)}, ${q(a.auth)}, ${q(a.checkTier)}, ${bool(a.https)}, ${cors(a.cors)}, ` +
      `${q(a.freeTier)}, ${q(a.rateLimit)}, ${bool(a.requiresCard)}, ${q(a.commercialUse)}, ` +
      `${q(a.dataLicense)}, ${q(a.status)}, ${q(a.addedAt)}, NULL, ${opt(a.diedAt)}, ${opt(a.epitaph)});`
  )
})

lines.push('')
lines.push('-- endpoints — catalog routes; only the monitored route is active for the health checker')
let endpointId = 1
const monitoredEndpointByApi = new Map<number, number>()
for (let apiId = 1; apiId <= apis.length; apiId++) {
  const a = apis[apiId - 1]!
  const schedulable = a.status !== 'dead' && a.checkTier !== 'listed'
  for (const ep of a.endpoints) {
    const url = endpointUrl(a.baseUrl, ep.path)
    const active = ep.monitored && schedulable ? 1 : 0
    if (ep.monitored) monitoredEndpointByApi.set(apiId, endpointId)
    lines.push(
      `insert into endpoints (id, api_id, method, url_template, sample_params_json, description, active) values ` +
        `(${endpointId}, ${apiId}, ${q(ep.method)}, ${q(url)}, NULL, ${q(ep.description)}, ${active});`
    )
    endpointId++
  }
}

lines.push('')
lines.push('-- shape_changes — hand-curated history; hashes NULL until real captures exist')
for (let apiId = 1; apiId <= apis.length; apiId++) {
  const a = apis[apiId - 1]!
  const epId = monitoredEndpointByApi.get(apiId)
  if (!epId) continue
  for (const sc of a.shapeChanges) {
    lines.push(
      `insert into shape_changes (endpoint_id, ts, old_hash, new_hash, diff_summary) values ` +
        `(${epId}, ${q(sc.date)}, NULL, NULL, ${q(sc.summary)});`
    )
  }
}

const out = fileURLToPath(new URL('../migrations/0002_seed.sql', import.meta.url))
writeFileSync(out, lines.join('\n') + '\n')
const totalEps = apis.reduce((n, a) => n + a.endpoints.length, 0)
console.log(`wrote ${out} — ${categories.length} categories, ${apis.length} apis, ${totalEps} endpoints`)
