// Generate probe hints by live-probing keyless candidates with expanded URL patterns.
// Successful discoveries append to scripts/lib/generated-hints.mjs for re-use.
// run: node scripts/generate-hints.mjs [--limit 400] [--concurrency 12]

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { readdirSync } from 'node:fs'
import {
  probeUrl, docsFetchUrl, extractProbeUrls, guessEndpoints, splitBaseAndEndpoint,
  isPostmanCollection, isOpenApiSpec, UA, slugify,
} from './lib/probe-utils.mjs'

const LIMIT = Number(process.argv.find((a, i) => process.argv[i - 1] === '--limit') || '1500')
const CONC = Number(process.argv.find((a, i) => process.argv[i - 1] === '--concurrency') || '16')
const OUT = fileURLToPath(new URL('./lib/generated-hints.mjs', import.meta.url))
const POOL_FILES = [
  fileURLToPath(new URL('./directory-candidates.json', import.meta.url)),
  fileURLToPath(new URL('./thorough-discovery.json', import.meta.url)),
  fileURLToPath(new URL('./extra-candidates.json', import.meta.url)),
]
const SEED = fileURLToPath(new URL('../src/data/seed.ts', import.meta.url))
const IMPORTED = fileURLToPath(new URL('../src/data/seed-imported.ts', import.meta.url))
const IMPORT_DIR = fileURLToPath(new URL('./import/', import.meta.url))

function hostKey(url) {
  try { return new URL(url).hostname.replace(/^www\./, '') } catch { return '' }
}

function hostAliases(host) {
  const h = host.replace(/^www\./, '')
  const out = new Set([h])
  if (h.startsWith('api.')) out.add(h.slice(4))
  else out.add(`api.${h}`)
  return [...out]
}

const known = new Set()
function register(url) {
  try { for (const a of hostAliases(new URL(url).hostname)) known.add(a) } catch { /* */ }
}

for (const f of [SEED, IMPORTED]) {
  for (const m of readFileSync(f, 'utf8').matchAll(/(?:docsUrl|baseUrl)"?\s*:\s*["'](https?:\/\/[^/"']+)/g)) register(m[1])
}
for (const f of readdirSync(IMPORT_DIR).filter((x) => /^batch-\d+\.json$/.test(x))) {
  for (const v of JSON.parse(readFileSync(IMPORT_DIR + f, 'utf8')).verified ?? []) register(v.baseUrl)
}

const pool = []
for (const path of POOL_FILES) {
  if (!existsSync(path)) continue
  pool.push(...(JSON.parse(readFileSync(path, 'utf8')).candidates ?? []))
}

// apiEngine + FreeAPI — structured sources with alive/no-auth flags
try {
  const ae = await fetch('https://raw.githubusercontent.com/germanter/apiEngine/main/api.json', {
    headers: { 'user-agent': UA },
  }).then((r) => r.json())
  const list = Array.isArray(ae) ? ae : (ae.apis ?? ae.data ?? [])
  for (const a of list) {
    const alive = a.s === 1 || a.status === 'ALIVE'
    const needsAuth = a.auth === true || a.a === true
    if (!alive || needsAuth) continue
    pool.push({
      name: a.name,
      docsUrl: a.url || a.u,
      description: a.desc || a.d || '',
      auth: 'none',
      https: String(a.url || a.u || '').startsWith('https'),
      sourceCategory: a.category || a.c || 'Development',
    })
  }
  console.log('apiEngine no-auth alive:', list.filter((a) => !a.auth && !a.a).length)
} catch (e) { console.warn('apiEngine:', e.message) }

try {
  const fa = await fetch('https://raw.githubusercontent.com/AIPMAndy/FreeAPI/main/apis.json', {
    headers: { 'user-agent': UA },
  }).then((r) => r.json())
  for (const [cat, list] of Object.entries(fa.categories ?? {})) {
    for (const e of list) {
      if (!/^no$/i.test(String(e.auth))) continue
      pool.push({
        name: e.name,
        docsUrl: e.url,
        description: e.description ?? '',
        auth: 'none',
        https: e.https !== false,
        sourceCategory: cat,
      })
    }
  }
} catch (e) { console.warn('FreeAPI:', e.message) }
const queue = []
const seen = new Set()
for (const c of pool) {
  if (c.auth !== 'none' || !c.https) continue
  let host
  try { host = hostKey(c.docsUrl) } catch { continue }
  if (hostAliases(host).some((h) => known.has(h))) continue
  const key = host + '|' + c.name.toLowerCase()
  if (seen.has(key)) continue
  seen.add(key)
  queue.push(c)
  if (queue.length >= LIMIT) break
}

console.log(`discovering hints from ${queue.length} keyless candidates...`)

function escStr(s) {
  return JSON.stringify(String(s ?? '').replace(/\s+/g, ' ').slice(0, 200))
}

function hintLine(h) {
  return `  { match: /${h.match}/i, name: ${escStr(h.name)}, emoji: '🔌', baseUrl: ${escStr(h.baseUrl)}, sampleEndpoint: ${escStr(h.sampleEndpoint)}, sourceCategory: ${escStr(h.sourceCategory)}, tagline: ${escStr(h.tagline)}, description: ${escStr(h.description)} },`
}

function writeHintsFile(hints) {
  const lines = hints.map(hintLine)
  writeFileSync(OUT, `// AUTO-GENERATED by scripts/generate-hints.mjs — ${new Date().toISOString()}\nexport const GENERATED_HINTS = [\n${lines.join('\n')}\n]\n`)
}

const hints = []
const MAX = 28

// preserve prior generated hints
try {
  const prev = await import('./lib/generated-hints.mjs?t=' + Date.now())
  for (const h of prev.GENERATED_HINTS ?? []) {
    hints.push({
      match: typeof h.match === 'string' ? h.match : h.match?.source?.replace(/^\^|\$$/g, '').replace(/\\/g, ''),
      name: h.name,
      baseUrl: h.baseUrl,
      sampleEndpoint: h.sampleEndpoint,
      sourceCategory: h.sourceCategory,
      tagline: h.tagline,
      description: h.description,
    })
    register(h.baseUrl)
  }
} catch { /* first run */ }

async function discover(c) {
  const urls = [...guessEndpoints(c)]
  try {
    const res = await fetch(docsFetchUrl(c.docsUrl), {
      signal: AbortSignal.timeout(6000),
      headers: { 'user-agent': UA, accept: 'text/html,*/*' },
    })
    if (res.ok) urls.unshift(...extractProbeUrls(await res.text(), 20))
  } catch { /* */ }

  const tried = new Set()
  for (const raw of urls) {
    if (tried.size >= MAX) break
    const url = raw.trim()
    if (!url || tried.has(url)) continue
    tried.add(url)
    const r = await probeUrl(url)
    if (r.httpStatus === 200 && r.json && !isPostmanCollection(r.json) && !isOpenApiSpec(r.json)) {
      const split = splitBaseAndEndpoint(url)
      if (!split) continue
      const host = hostKey(split.baseUrl)
      const esc = c.name.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
      hints.push({
        match: host.replace(/\./g, '\\.'),
        name: c.name,
        baseUrl: split.baseUrl,
        sampleEndpoint: split.sampleEndpoint,
        sourceCategory: c.sourceCategory || 'Development',
        tagline: `${c.name} — auto-discovered JSON endpoint`,
        description: c.description || `${c.name} keyless JSON API verified by automated discovery.`,
      })
      register(split.baseUrl)
      process.stdout.write(`  ✓ ${c.name}\n`)
      // checkpoint every 10 discoveries
      if (hints.length % 10 === 0) writeHintsFile(hints)
      return
    }
  }
}

const work = [...queue]
await Promise.all(Array.from({ length: CONC }, async () => {
  for (let c; (c = work.shift()); ) await discover(c)
}))

writeHintsFile(hints)

console.log(`\nwrote ${hints.length} hints → ${OUT}`)
