// Seed catalog for local UI development.
// Deterministic pseudo-random health data so every reload renders identical charts.
// In production this module is replaced by D1 queries; keep the shapes aligned with MASTERPLAN §5.1.

// Imported keyless APIs (public-apis list, each probe-verified at import). Generated by
// scripts/assemble-seed.mjs — status 'unmonitored', no synthetic health. Runtime dep is one-way
// (this file → seed-imported); seed-imported only imports our TYPES back, so there's no cycle.
import { applyEndpointRecipe } from '../../scripts/lib/endpoint-recipes.mjs'
import { inferCheckTier, type CheckTier } from './check-tier.ts'
import { importedCategories, importedSpecs } from './seed-imported.ts'

export type { CheckTier } from './check-tier.ts'

export type LifecycleStatus =
  | 'healthy'
  | 'degraded'
  | 'dying'
  | 'dead'
  | 'new'
  | 'resurrected'
  | 'unmonitored'

export interface Category {
  slug: string
  name: string
  emoji: string
  blurb: string
}

export interface ShapeChange {
  date: string
  summary: string
}

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export interface ApiEndpoint {
  method: HttpMethod
  path: string
  description: string
  /** The path our health checker probes — exactly one per API. */
  monitored?: boolean
}

export interface ApiEntry {
  slug: string
  name: string
  emoji: string
  tagline: string
  description: string
  category: string
  docsUrl: string
  baseUrl: string
  sampleEndpoint: string
  endpoints: ApiEndpoint[]
  auth: 'none' | 'apiKey' | 'oauth' | 'userAgent' // userAgent: keyless but an identified UA is required (Nominatim-class etiquette)
  /** What we actually check — endpoint (2xx JSON), reachability (401 wall), docs, or listed only. */
  checkTier: CheckTier
  https: boolean
  cors: 'yes' | 'no' | 'unknown'
  // Can a non-browser client (our shipapisbot UA) actually reach it, or does a WAF/bot-wall block it?
  // 'ok' = last probe got through · 'blocked' = bot_challenge observed · 'unknown' = not yet confirmed.
  agentAccess: 'ok' | 'blocked' | 'unknown'
  commercialUse: 'yes' | 'no' | 'unclear'
  dataLicense: string
  freeTier: string
  rateLimit: string
  requiresCard: boolean
  status: LifecycleStatus
  healthScore: number
  monitoredSince: string | null // ISO date the first real check landed; null until monitored (Δ2 gate)
  uptime90: number[] // fraction of checks OK per day, oldest→newest; -1 = not monitored yet
  latency48: number[] // ms per check, last 48 checks
  p50: number
  p95: number
  lastCheckedMin: number
  addedAt: string
  sample: unknown
  shapeChanges: ShapeChange[]
  diedAt?: string
  epitaph?: string
  /** How each metadata field was sourced — drives honest labels on the detail page. */
  metaProvenance?: {
    auth: 'probed' | 'documented' | 'pending'
    cors: 'probed' | 'import' | 'pending'
    commercialUse: 'documented' | 'pending'
    https: 'probed' | 'documented'
    freeTier: 'documented' | 'pending'
    rateLimit: 'probed' | 'documented' | 'pending'
  }
}

// ---------------------------------------------------------------------------

function mulberry32(seed: number) {
  let a = seed >>> 0
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function hashSeed(s: string) {
  let h = 2166136261
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return h >>> 0
}

function uptimeSeries(slug: string, profile: LifecycleStatus): number[] {
  const rand = mulberry32(hashSeed(slug))
  const days: number[] = []
  for (let d = 0; d < 90; d++) {
    const r = rand()
    let v: number
    switch (profile) {
      case 'healthy':
        v = r < 0.94 ? 1 : r < 0.985 ? 0.995 - rand() * 0.02 : 0.94 + rand() * 0.04
        break
      case 'degraded':
        // fine historically, rough last ~2 weeks
        v = d < 74 ? (r < 0.92 ? 1 : 0.97 + rand() * 0.02) : r < 0.45 ? 0.55 + rand() * 0.3 : 0.86 + rand() * 0.1
        break
      case 'dying':
        v = d < 55 ? (r < 0.9 ? 1 : 0.96) : Math.max(0, 0.85 - (d - 55) * 0.024 + (rand() - 0.5) * 0.1)
        break
      case 'dead':
        v = d < 30 ? (r < 0.85 ? 1 : 0.95) : d < 38 ? Math.max(0, 0.6 - (d - 30) * 0.08) : 0
        break
      case 'new':
        v = d < 76 ? -1 : r < 0.9 ? 1 : 0.98
        break
      case 'resurrected':
        v = d < 40 ? 0 : d < 46 ? 0.5 + (d - 40) * 0.08 : r < 0.9 ? 1 : 0.97
        break
      default:
        v = -1
    }
    days.push(v === -1 ? -1 : Math.min(1, Math.max(0, Math.round(v * 1000) / 1000)))
  }
  return days
}

function latencySeries(slug: string, base: number, spiky = false): number[] {
  const rand = mulberry32(hashSeed(slug + ':lat'))
  const out: number[] = []
  for (let i = 0; i < 48; i++) {
    const jitter = (rand() - 0.5) * base * 0.3
    const spike = spiky && rand() > 0.93 ? base * (1.5 + rand() * 2) : 0
    out.push(Math.max(18, Math.round(base + jitter + spike)))
  }
  return out
}

function percentile(sorted: number[], p: number) {
  const idx = Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length))
  return sorted[idx]
}

export interface ApiSpec
  extends Omit<ApiEntry, 'uptime90' | 'latency48' | 'p50' | 'p95' | 'healthScore' | 'endpoints' | 'agentAccess' | 'monitoredSince' | 'checkTier'> {
  baseLatency: number
  spiky?: boolean
  healthScore?: number
  /** Override inferred check tier (demo-key apiKey → endpoint, signup-key → reachability). */
  checkTier?: CheckTier
  /** Curated endpoint list. Omit to derive a single monitored GET from sampleEndpoint. */
  endpoints?: ApiEndpoint[]
  /** Omit to derive: unmonitored → 'unknown' (not yet probed by us), else 'ok'. Checker maintains it live. */
  agentAccess?: 'ok' | 'blocked' | 'unknown'
}

function defaultEndpoints(spec: Pick<ApiSpec, 'sampleEndpoint' | 'tagline'>): ApiEndpoint[] {
  return [
    {
      method: 'GET',
      path: spec.sampleEndpoint,
      description: spec.tagline || 'Documented sample GET — verified by our probe.',
      monitored: true,
    },
  ]
}

function resolveEndpoints(spec: ApiSpec): ApiEndpoint[] {
  if (spec.endpoints?.length) return spec.endpoints.map((e) => ({ ...e }))
  const expanded = applyEndpointRecipe({
    slug: spec.slug,
    baseUrl: spec.baseUrl,
    sampleEndpoint: spec.sampleEndpoint,
    tagline: spec.tagline,
  })
  if (expanded.endpoints?.length) return expanded.endpoints as ApiEndpoint[]
  return defaultEndpoints(spec)
}

/** Full callable URL for an endpoint path relative to baseUrl. */
export function endpointUrl(baseUrl: string, path: string) {
  if (/^https?:\/\//i.test(path)) return path
  const base = baseUrl.replace(/\/+$/, '')
  const p = path.startsWith('/') ? path : `/${path}`
  return base + p
}

export function build(spec: ApiSpec): ApiEntry {
  const uptime90 = uptimeSeries(spec.slug, spec.status)
  // dead + unmonitored carry no monitoring latency series. An unmonitored import was probed once,
  // but a single sample isn't a p50/p95 distribution — so we surface none (p50=0 → '—'/null everywhere).
  const latency48 =
    spec.status === 'dead' || spec.status === 'unmonitored'
      ? []
      : latencySeries(spec.slug, spec.baseLatency, spec.spiky)
  const sorted = [...latency48].sort((a, b) => a - b)
  const monitored = uptime90.filter((v) => v >= 0)
  const uptimeAvg = monitored.length ? monitored.reduce((a, b) => a + b, 0) / monitored.length : 0
  const p50 = sorted.length ? percentile(sorted, 50) : 0
  const p95 = sorted.length ? percentile(sorted, 95) : 0
  // MASTERPLAN §6.6 — published formula: uptime 60% · latency vs category median 20% · shape stability 20%
  const latencyFactor = Math.max(0, Math.min(1, 1 - (p50 - 120) / 1200))
  const stability = Math.max(0, 1 - spec.shapeChanges.length * 0.12)
  const computed = Math.round((uptimeAvg * 0.6 + latencyFactor * 0.2 + stability * 0.2) * 100)
  const endpoints = resolveEndpoints(spec)
  if (!endpoints.some((e) => e.monitored)) endpoints[0]!.monitored = true
  const checkTier = inferCheckTier({
    auth: spec.auth,
    sampleEndpoint: spec.sampleEndpoint,
    status: spec.status,
    checkTier: spec.checkTier,
    docsUrl: spec.docsUrl,
  })
  return {
    ...spec,
    checkTier,
    endpoints,
    uptime90,
    latency48,
    p50,
    p95,
    // -1 = not scored yet (unmonitored imports have no history); dead pins to 0; else the formula.
    healthScore:
      spec.status === 'dead' ? 0 : spec.status === 'unmonitored' ? -1 : (spec.healthScore ?? computed),
    // Not yet confirmed for unmonitored records; our import/checks probe with the bot UA, so else 'ok'.
    agentAccess: spec.agentAccess ?? (spec.status === 'unmonitored' ? 'unknown' : 'ok'),
    // Seed fixture is never "really" monitored; the D1 catalog overlays the real date (Δ2 gate).
    monitoredSince: null,
  }
}

// ---------------------------------------------------------------------------

export const categories: Category[] = [
  { slug: 'weather', name: 'Weather', emoji: '🌦', blurb: 'Forecasts, climate history and severe-weather feeds — checked around the clock.' },
  { slug: 'finance', name: 'Finance', emoji: '📈', blurb: 'FX, crypto and market data with the free-tier fine print actually verified.' },
  { slug: 'geo', name: 'Geo & Maps', emoji: '🗺', blurb: 'Geocoding, IP location and country data. Rate limits documented, not guessed.' },
  { slug: 'science', name: 'Science & Space', emoji: '🔭', blurb: 'Space, physics and research data from agencies and observatories.' },
  { slug: 'animals', name: 'Animals', emoji: '🐕', blurb: 'The classics — every image endpoint verified to still return an actual dog.' },
  { slug: 'fun', name: 'Fun', emoji: '😄', blurb: 'Jokes, quotes, memes and trivia — the delightful throwaway stuff for demos and toy projects.' },
  { slug: 'data', name: 'Open Data', emoji: '📚', blurb: 'Books, countries, encyclopedic and public datasets with stable schemas.' },
  { slug: 'developer', name: 'Developer Tools', emoji: '🔧', blurb: 'Utilities you wire into everything else — IPs, avatars, placeholders, QR.' },
  ...importedCategories,
]

export const apis: ApiEntry[] = [
  build({
    slug: 'open-meteo',
    name: 'Open-Meteo',
    emoji: '🌤',
    tagline: 'Hourly forecasts for any coordinate — no key, no signup.',
    description:
      'Open-Meteo serves fast global weather forecasts assembled from national weather services. The free endpoint needs no API key, answers over HTTPS with permissive CORS, and covers hourly and daily variables, historical reanalysis and air quality. Note the license: the free tier is for non-commercial use — a paid keyed tier exists for products.',
    category: 'weather',
    docsUrl: 'https://open-meteo.com/en/docs',
    baseUrl: 'https://api.open-meteo.com/v1',
    sampleEndpoint: '/forecast?latitude=52.52&longitude=13.41&current=temperature_2m,wind_speed_10m',
    endpoints: [
      {
        method: 'GET',
        path: '/forecast?latitude=52.52&longitude=13.41&current=temperature_2m,wind_speed_10m',
        description: 'Hourly and daily forecasts for any coordinate — the primary weather call.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m,precipitation',
        description: 'Hourly variables — temperature, humidity, wind, precipitation.',
      },
      {
        method: 'GET',
        path: '/air-quality?latitude=52.52&longitude=13.41&current=us_aqi,pm2_5',
        description: 'Current air-quality index and pollutant concentrations.',
      },
      {
        method: 'GET',
        path: '/elevation?latitude=52.52&longitude=13.41',
        description: 'Terrain elevation in meters for a coordinate.',
      },
    ],
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'no',
    dataLicense: 'CC-BY 4.0',
    freeTier: '<10,000 calls/day, no signup',
    rateLimit: '600/min · 5,000/hour',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 4,
    baseLatency: 96,
    sample: {
      latitude: 52.52,
      longitude: 13.41,
      elevation: 38.0,
      current: { time: '2026-07-04T02:15', temperature_2m: 17.3, wind_speed_10m: 9.4 },
      current_units: { temperature_2m: '°C', wind_speed_10m: 'km/h' },
    },
    shapeChanges: [],
  }),
  build({
    slug: 'frankfurter',
    name: 'Frankfurter',
    emoji: '💱',
    tagline: 'Central-bank FX rates. MIT-licensed, self-hostable, commercial-safe.',
    description:
      'Frankfurter tracks reference exchange rates from the European Central Bank and friends. It is the rare free API with zero strings attached: MIT-licensed code, self-hostable via Docker, explicit yes to commercial use, and no quotas beyond abuse-prevention rate limiting. The gold standard for what a free API should be.',
    category: 'finance',
    docsUrl: 'https://frankfurter.dev',
    baseUrl: 'https://api.frankfurter.dev/v1',
    sampleEndpoint: '/latest?base=USD&symbols=EUR,GBP,JPY',
    endpoints: [
      {
        method: 'GET',
        path: '/latest?base=USD&symbols=EUR,GBP,JPY',
        description: 'Latest reference FX rates from ECB sources — commercial-safe.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/2024-01-15?base=USD&symbols=EUR',
        description: 'Historical rates for a specific ISO date.',
      },
      {
        method: 'GET',
        path: '/currencies',
        description: 'List all supported currency codes.',
      },
    ],
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'yes',
    dataLicense: 'Public data (ECB reference rates)',
    freeTier: 'Unlimited — abuse-rate-limited only',
    rateLimit: 'Unpublished, generous',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 7,
    baseLatency: 84,
    sample: {
      amount: 1.0,
      base: 'USD',
      date: '2026-07-03',
      rates: { EUR: 0.9207, GBP: 0.7811, JPY: 158.42 },
    },
    shapeChanges: [],
  }),
  build({
    slug: 'coingecko',
    name: 'CoinGecko',
    emoji: '🦎',
    tagline: 'Crypto prices and market data with a real free demo tier.',
    description:
      'CoinGecko exposes coin prices, market charts and exchange data. The free demo tier works without a card but enforces strict per-minute limits that tighten during market volatility — our checks catch the throttling windows other directories miss. Response shapes have shifted twice this year; see the change log below.',
    category: 'finance',
    docsUrl: 'https://docs.coingecko.com',
    baseUrl: 'https://api.coingecko.com/api/v3',
    sampleEndpoint: '/simple/price?ids=bitcoin&vs_currencies=usd',
    endpoints: [
      {
        method: 'GET',
        path: '/simple/price?ids=bitcoin&vs_currencies=usd',
        description: 'Spot price for one or more coin IDs — the workhorse demo call.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10',
        description: 'Top coins by market cap with 24h change and volume.',
      },
      {
        method: 'GET',
        path: '/coins/bitcoin/market_chart?vs_currency=usd&days=7',
        description: 'Historical price, market cap and volume series.',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'yes',
    commercialUse: 'unclear',
    dataLicense: 'Proprietary — attribution required',
    freeTier: '10k calls/mo demo key, no card',
    rateLimit: '~30/min, tightens under load',
    requiresCard: false,
    status: 'degraded',
    addedAt: '2026-05-02',
    lastCheckedMin: 2,
    baseLatency: 310,
    spiky: true,
    sample: { bitcoin: { usd: 118423 } },
    shapeChanges: [
      { date: '2026-06-19', summary: 'Rate-limit headers renamed: x-cg-* → x-ratelimit-*' },
      { date: '2026-03-08', summary: 'simple/price gained optional `last_updated_at` field' },
    ],
  }),
  build({
    slug: 'rest-countries',
    name: 'REST Countries',
    emoji: '🌍',
    tagline: 'Every country as clean JSON — flags, currencies, borders.',
    description:
      'REST Countries answers with structured data for all 250 country codes: names, capitals, currencies, languages, borders and flag assets. Community-run and donation-funded, which our monitoring treats honestly: it is reliable but occasionally slow under load, and v3 broke v2 consumers — shape history below.',
    category: 'data',
    docsUrl: 'https://restcountries.com',
    baseUrl: 'https://restcountries.com/v3.1',
    sampleEndpoint: '/name/ghana?fields=name,capital,currencies,flags',
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'yes',
    dataLicense: 'MPL-2.0',
    freeTier: 'Unlimited',
    rateLimit: 'None published',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 11,
    baseLatency: 188,
    spiky: true,
    sample: {
      name: { common: 'Ghana', official: 'Republic of Ghana' },
      capital: ['Accra'],
      currencies: { GHS: { name: 'Ghanaian cedi', symbol: '₵' } },
      flags: { png: 'https://flagcdn.com/w320/gh.png' },
    },
    shapeChanges: [{ date: '2026-01-22', summary: 'v2 endpoints removed — v3.1 required' }],
  }),
  build({
    slug: 'nominatim',
    name: 'Nominatim (OSM)',
    emoji: '📍',
    tagline: 'OpenStreetMap geocoding — powerful, with strict etiquette.',
    description:
      'Nominatim turns addresses into coordinates and back using OpenStreetMap data. The public instance is free but governed by a strict usage policy: one request per second per application, a real User-Agent, and no heavy or commercial-primary use — self-host for that. We surface those terms up front because violating them gets apps banned.',
    category: 'geo',
    docsUrl: 'https://nominatim.org/release-docs/latest/api/Overview/',
    baseUrl: 'https://nominatim.openstreetmap.org',
    sampleEndpoint: '/search?q=Accra&format=jsonv2&limit=1',
    endpoints: [
      {
        method: 'GET',
        path: '/search?q=Accra&format=jsonv2&limit=1',
        description: 'Forward geocode a place name to coordinates and OSM metadata.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/reverse?lat=5.6037&lon=-0.1870&format=jsonv2',
        description: 'Reverse geocode coordinates to a human-readable address.',
      },
      {
        method: 'GET',
        path: '/lookup?osm_ids=R123456&format=jsonv2',
        description: 'Look up a place by OpenStreetMap object ID.',
      },
    ],
    auth: 'userAgent',
    https: true,
    cors: 'yes',
    commercialUse: 'no',
    dataLicense: 'ODbL (OpenStreetMap)',
    freeTier: '1 req/sec, identified UA required',
    rateLimit: '1/sec hard — per application',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 9,
    baseLatency: 240,
    sample: [
      {
        place_id: 2584114,
        display_name: 'Accra, Greater Accra Region, Ghana',
        lat: '5.5571096',
        lon: '-0.2012376',
        type: 'city',
      },
    ],
    shapeChanges: [],
  }),
  build({
    slug: 'pokeapi',
    name: 'PokéAPI',
    emoji: '⚡',
    tagline: 'The Pokémon dataset every tutorial is built on.',
    description:
      'PokéAPI serves the full Pokémon universe — species, moves, types, sprites — as deeply linked JSON. It is the most-taught API on the internet and holds up under that traffic remarkably well. Fully static-cached, so latency is excellent worldwide.',
    category: 'games',
    docsUrl: 'https://pokeapi.co/docs/v2',
    baseUrl: 'https://pokeapi.co/api/v2',
    sampleEndpoint: '/pokemon/pikachu',
    endpoints: [
      {
        method: 'GET',
        path: '/pokemon/pikachu',
        description: 'Full Pokémon record — stats, types, sprites and evolution chain link.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/pokemon?limit=20&offset=0',
        description: 'Paginated list of all Pokémon resource URLs.',
      },
      {
        method: 'GET',
        path: '/type/fire',
        description: 'Type metadata and the Pokémon that share it.',
      },
    ],
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'no',
    dataLicense: 'Fair-use fan data',
    freeTier: 'Unlimited (be reasonable)',
    rateLimit: 'None — locally cache please',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 5,
    baseLatency: 72,
    sample: {
      id: 25,
      name: 'pikachu',
      height: 4,
      weight: 60,
      types: [{ slot: 1, type: { name: 'electric' } }],
    },
    shapeChanges: [],
  }),
  build({
    slug: 'nasa-apod',
    name: 'NASA APOD',
    emoji: '🪐',
    tagline: 'Astronomy Picture of the Day, straight from NASA.',
    description:
      'NASA’s Astronomy Picture of the Day API returns the daily image with its explanation and metadata. A DEMO_KEY works instantly for prototyping; a free personal key raises the limits. Public-domain data, explicit yes to commercial use — one of the friendliest licenses in the catalog.',
    category: 'science',
    docsUrl: 'https://api.nasa.gov',
    baseUrl: 'https://api.nasa.gov/planetary',
    sampleEndpoint: '/apod?api_key=DEMO_KEY',
    auth: 'apiKey',
    https: true,
    cors: 'yes',
    commercialUse: 'yes',
    dataLicense: 'Public domain (US Gov)',
    freeTier: '1,000 req/hour with free key',
    rateLimit: 'DEMO_KEY: 30/hour, 50/day',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 13,
    baseLatency: 410,
    sample: {
      date: '2026-07-03',
      title: 'The Heart Nebula in Hydrogen and Oxygen',
      media_type: 'image',
      url: 'https://apod.nasa.gov/apod/image/2607/HeartNebula.jpg',
    },
    shapeChanges: [],
  }),
  build({
    slug: 'open-library',
    name: 'Open Library',
    emoji: '📖',
    tagline: 'Books, authors and covers from the Internet Archive.',
    description:
      'Open Library exposes bibliographic data for tens of millions of books — search, works, editions, covers — maintained by the Internet Archive. Great for reading apps and coursework. Bulk users should download the data dumps instead of crawling the API.',
    category: 'data',
    docsUrl: 'https://openlibrary.org/developers/api',
    baseUrl: 'https://openlibrary.org',
    sampleEndpoint: '/search.json?q=things+fall+apart&limit=1',
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'unclear',
    dataLicense: 'Mixed — mostly open',
    freeTier: 'Unlimited within courtesy limits',
    rateLimit: 'Soft — identified UA appreciated',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 21,
    baseLatency: 520,
    spiky: true,
    sample: {
      numFound: 214,
      docs: [{ title: 'Things Fall Apart', author_name: ['Chinua Achebe'], first_publish_year: 1958 }],
    },
    shapeChanges: [],
  }),
  build({
    slug: 'ipify',
    name: 'ipify',
    emoji: '🔌',
    tagline: 'Your public IP as JSON. One job, done perfectly.',
    description:
      'ipify returns the caller’s public IP address. That is the entire API — which is exactly why it appears in half the networking tutorials ever written. Unlimited, CORS-open, commercial-friendly, and in five years of community memory it has effectively never been down.',
    category: 'developer',
    docsUrl: 'https://www.ipify.org',
    baseUrl: 'https://api.ipify.org',
    sampleEndpoint: '/?format=json',
    endpoints: [
      { method: 'GET', path: '/?format=json', description: 'Your public IPv4 or IPv6 address as JSON.', monitored: true },
      { method: 'GET', path: '/?format=json&callback=getIP', description: 'JSONP variant for legacy browser scripts.' },
    ],
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'yes',
    dataLicense: 'n/a',
    freeTier: 'Unlimited',
    rateLimit: 'None',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 3,
    baseLatency: 48,
    sample: { ip: '154.160.1.24' },
    shapeChanges: [],
  }),
  build({
    slug: 'agify',
    name: 'Agify',
    emoji: '🎂',
    tagline: 'Predicts age from a first name. Weirdly useful for demos.',
    description:
      'Agify estimates a person’s age from their first name using aggregated census-style data. It is the canonical “my first fetch()” API: no key, instant JSON, CORS everywhere. Free tier covers 100 names a day; the paid tier is rarely needed outside batch jobs.',
    category: 'fun',
    docsUrl: 'https://agify.io',
    baseUrl: 'https://api.agify.io',
    sampleEndpoint: '/?name=kwame',
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'yes',
    dataLicense: 'Proprietary',
    freeTier: '100 names/day, no signup',
    rateLimit: '100/day per IP',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 6,
    baseLatency: 110,
    sample: { name: 'kwame', age: 34, count: 12841 },
    shapeChanges: [],
  }),
  build({
    slug: 'dog-ceo',
    name: 'Dog CEO',
    emoji: '🐶',
    tagline: '20,000+ open-source dog photos by breed.',
    description:
      'Dog CEO serves random dog images from the Stanford Dogs dataset, browsable by breed and sub-breed. Community-run and donation-backed. The single most wholesome endpoint in this directory, and our uptime data proves the dogs are dependable.',
    category: 'animals',
    docsUrl: 'https://dog.ceo/dog-api/',
    baseUrl: 'https://dog.ceo/api',
    sampleEndpoint: '/breeds/image/random',
    endpoints: [
      {
        method: 'GET',
        path: '/breeds/image/random',
        description: 'Random dog photo URL from the full breed catalog.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/breeds/list/all',
        description: 'Every breed and sub-breed as a nested JSON map.',
      },
      {
        method: 'GET',
        path: '/breed/hound/images',
        description: 'All image URLs for a specific breed.',
      },
    ],
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'yes',
    dataLicense: 'Stanford Dogs dataset',
    freeTier: 'Unlimited',
    rateLimit: 'None published',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-02',
    lastCheckedMin: 8,
    baseLatency: 132,
    sample: {
      message: 'https://images.dog.ceo/breeds/shiba/shiba-16.jpg',
      status: 'success',
    },
    shapeChanges: [],
  }),
  build({
    slug: 'wikipedia-rest',
    name: 'Wikipedia REST',
    emoji: '📰',
    tagline: 'Page summaries and extracts for anything on Wikipedia.',
    description:
      'Wikimedia’s REST API returns clean page summaries — title, extract, thumbnail — perfect for hover cards and enrichment. Backed by Wikimedia’s serious infrastructure, so it is one of the most reliable free endpoints anywhere. Respect the etiquette: identified User-Agent, modest concurrency.',
    category: 'data',
    docsUrl: 'https://en.wikipedia.org/api/rest_v1/',
    baseUrl: 'https://en.wikipedia.org/api/rest_v1',
    sampleEndpoint: '/page/summary/Accra',
    endpoints: [
      {
        method: 'GET',
        path: '/page/summary/Accra',
        description: 'Lead extract, thumbnail and metadata for a Wikipedia page title.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/page/mobile-sections/Accra',
        description: 'Mobile-formatted article sections for in-app readers.',
      },
      {
        method: 'GET',
        path: '/page/media-list/Accra',
        description: 'Images and media attached to a page.',
      },
    ],
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'yes',
    dataLicense: 'CC BY-SA 4.0',
    freeTier: 'Unlimited within etiquette',
    rateLimit: '200/sec global courtesy cap',
    requiresCard: false,
    status: 'healthy',
    addedAt: '2026-05-09',
    lastCheckedMin: 15,
    baseLatency: 92,
    sample: {
      title: 'Accra',
      description: 'Capital city of Ghana',
      extract: 'Accra is the capital and largest city of Ghana…',
    },
    shapeChanges: [],
  }),
  build({
    slug: 'open-notify',
    name: 'Open Notify',
    emoji: '🛰',
    tagline: 'Where is the ISS right now? A beloved API in decline.',
    description:
      'Open Notify reports the live position of the International Space Station and who is in space. A classroom classic for a decade — but it is a single volunteer-run box, HTTP-only, and our checks show error rates climbing for weeks. Status: DYING. We list honest replacements below; consider wheretheiss.at.',
    category: 'science',
    docsUrl: 'http://open-notify.org',
    baseUrl: 'http://api.open-notify.org',
    sampleEndpoint: '/iss-now.json',
    auth: 'none',
    https: false,
    cors: 'no',
    commercialUse: 'unclear',
    dataLicense: 'n/a',
    freeTier: 'Unlimited (volunteer-run)',
    rateLimit: 'Please be gentle',
    requiresCard: false,
    status: 'dying',
    addedAt: '2026-05-02',
    lastCheckedMin: 12,
    baseLatency: 680,
    spiky: true,
    sample: {
      message: 'success',
      iss_position: { latitude: '-12.4021', longitude: '43.5591' },
      timestamp: 1751595300,
    },
    shapeChanges: [],
  }),
  build({
    slug: 'sunrise-sunset',
    name: 'Sunrise-Sunset',
    emoji: '🌅',
    tagline: 'Golden hour, civil twilight and day length for any point.',
    description:
      'Returns sunrise, sunset and twilight times for any coordinates and date. No key required. Recently added to the directory — the NEW badge means it has under two weeks of monitoring history, so treat the early numbers gently.',
    category: 'weather',
    docsUrl: 'https://sunrise-sunset.org/api',
    baseUrl: 'https://api.sunrise-sunset.org',
    sampleEndpoint: '/json?lat=5.6037&lng=-0.1870',
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'unclear',
    dataLicense: 'n/a',
    freeTier: 'Unlimited, attribution requested',
    rateLimit: 'No burst traffic',
    requiresCard: false,
    status: 'new',
    addedAt: '2026-06-22',
    lastCheckedMin: 10,
    baseLatency: 205,
    sample: {
      results: { sunrise: '5:58:11 AM', sunset: '6:07:42 PM', day_length: '12:09:31' },
      status: 'OK',
    },
    shapeChanges: [],
  }),
  build({
    slug: 'coindesk-bpi',
    name: 'CoinDesk BPI',
    emoji: '🪦',
    tagline: 'The Bitcoin Price Index that powered a thousand tutorials.',
    description:
      'CoinDesk’s free Bitcoin Price Index was the default “first crypto API” for a decade of blog posts. The v1 endpoint was retired and now refuses connections entirely. Archived here with its final known response shape so old tutorials can be understood — and updated.',
    category: 'finance',
    docsUrl: 'https://www.coindesk.com',
    baseUrl: 'https://api.coindesk.com/v1',
    sampleEndpoint: '/bpi/currentprice.json',
    auth: 'none',
    https: true,
    cors: 'yes',
    commercialUse: 'no',
    dataLicense: 'Proprietary',
    freeTier: 'Was: unlimited',
    rateLimit: '—',
    requiresCard: false,
    status: 'dead',
    addedAt: '2026-05-02',
    lastCheckedMin: 31,
    baseLatency: 0,
    diedAt: '2026-05-14',
    epitaph: 'Ten thousand tutorials called. Nobody answered.',
    sample: {
      time: { updated: 'May 13, 2026 21:04:00 UTC' },
      bpi: { USD: { code: 'USD', rate_float: 104211.87 } },
    },
    shapeChanges: [{ date: '2026-05-14', summary: 'Connection refused — endpoint retired' }],
  }),
  build({
    slug: 'chartlyrics',
    name: 'ChartLyrics',
    emoji: '🪦',
    tagline: 'Song lyrics over SOAP/REST, from a gentler internet.',
    description:
      'ChartLyrics offered lyric search back when SOAP was still a reasonable word to say out loud. The API now returns 404 on all documented routes and the domain serves a parking page. Archived with its last known shape. Rest easy.',
    category: 'media',
    docsUrl: 'http://www.chartlyrics.com/api.aspx',
    baseUrl: 'http://api.chartlyrics.com',
    sampleEndpoint: '/apiv1.asmx/SearchLyricDirect',
    auth: 'none',
    https: false,
    cors: 'unknown',
    commercialUse: 'unclear',
    dataLicense: 'Unlicensed lyrics data',
    freeTier: 'Was: unlimited',
    rateLimit: '—',
    requiresCard: false,
    status: 'dead',
    addedAt: '2026-05-02',
    lastCheckedMin: 44,
    baseLatency: 0,
    diedAt: '2026-06-02',
    epitaph: '404: the music finally stopped.',
    sample: { LyricSong: 'Yellow', LyricArtist: 'Coldplay', Lyric: '(archived)' },
    shapeChanges: [{ date: '2026-06-02', summary: 'All routes 404 — domain parked' }],
  }),
  build({
    slug: 'omdb',
    name: 'OMDb',
    emoji: '🎞',
    tagline: 'Movie and series metadata by title or IMDb ID.',
    description:
      'The Open Movie Database returns plot, cast, ratings, runtime and poster art for films and shows. Query by title or tt-prefixed IMDb ID. Free tier with a personal key from omdbapi.com; the public patron key `trilogy` works for prototyping.',
    category: 'media',
    docsUrl: 'https://www.omdbapi.com/',
    baseUrl: 'https://www.omdbapi.com',
    sampleEndpoint: '/?t=Inception&apikey=trilogy',
    endpoints: [
      {
        method: 'GET',
        path: '/?t=Inception&apikey=trilogy',
        description: 'Lookup by title — plot, cast, ratings and poster.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/?i=tt1375666&apikey=trilogy',
        description: 'Lookup by IMDb ID (tt-prefixed).',
      },
      {
        method: 'GET',
        path: '/?s=batman&type=movie&apikey=trilogy',
        description: 'Search movies and series by keyword.',
      },
      {
        method: 'GET',
        path: '/?t=Inception&plot=full&apikey=trilogy',
        description: 'Full plot text instead of the short summary.',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'unknown',
    commercialUse: 'unclear',
    dataLicense: 'Community-contributed metadata',
    freeTier: '1,000 req/day free key',
    rateLimit: 'Patron key `trilogy` is shared — cache responses',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'endpoint',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 900,
    sample: {
      Title: 'Inception',
      Year: '2010',
      imdbID: 'tt1375666',
      Type: 'movie',
      Response: 'True',
    },
    shapeChanges: [],
  }),
  build({
    slug: 'tmdb',
    name: 'TMDb',
    emoji: '🎬',
    tagline: 'Community movie and TV metadata at scale.',
    description:
      'The Movie Database powers posters, cast, ratings, discover feeds and image CDN URLs for films and shows. Free API key after signup at themoviedb.org. Attribution required; commercial use needs separate approval from TMDb.',
    category: 'media',
    docsUrl: 'https://developer.themoviedb.org/docs',
    baseUrl: 'https://api.themoviedb.org/3',
    sampleEndpoint: '/movie/550?api_key=YOUR_API_KEY',
    endpoints: [
      {
        method: 'GET',
        path: '/movie/550?api_key=YOUR_API_KEY',
        description: 'Full movie record — cast, crew, images and metadata.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/movie/popular?api_key=YOUR_API_KEY',
        description: 'Paginated list of popular movies right now.',
      },
      {
        method: 'GET',
        path: '/tv/1399?api_key=YOUR_API_KEY',
        description: 'TV series details by TMDb ID (example: Game of Thrones).',
      },
      {
        method: 'GET',
        path: '/search/multi?query=inception&api_key=YOUR_API_KEY',
        description: 'Search movies, TV and people in one call.',
      },
      {
        method: 'GET',
        path: '/trending/movie/day?api_key=YOUR_API_KEY',
        description: 'Trending movies in the daily window.',
      },
      {
        method: 'GET',
        path: '/movie/550/watch/providers?api_key=YOUR_API_KEY',
        description: 'Streaming availability by country for a movie.',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'yes',
    commercialUse: 'no',
    dataLicense: 'TMDb terms — attribution required',
    freeTier: 'Free personal API key',
    rateLimit: '~50 req/sec documented ceiling',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'reachability',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 0,
    sample: {
      id: 550,
      title: 'Fight Club',
      release_date: '1999-10-15',
      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.',
    },
    shapeChanges: [],
  }),
  build({
    slug: 'fanart-tv',
    name: 'Fanart.tv',
    emoji: '🖼',
    tagline: 'HD logos, posters and backgrounds for media libraries.',
    description:
      'Fanart.tv serves artwork keyed by TMDB, TVDB or MusicBrainz IDs — ideal for Plex, Kodi and home-theater apps. Free API key after signup. Responses are JSON lists of image URLs with language and vote metadata.',
    category: 'media',
    docsUrl: 'https://fanart.tv/api-docs/',
    baseUrl: 'https://webservice.fanart.tv/v3',
    sampleEndpoint: '/movies/550?api_key=YOUR_API_KEY',
    endpoints: [
      {
        method: 'GET',
        path: '/movies/550?api_key=YOUR_API_KEY',
        description: 'Movie artwork — posters, logos and backgrounds.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/tv/1399?api_key=YOUR_API_KEY',
        description: 'TV series artwork by TVDB ID.',
      },
      {
        method: 'GET',
        path: '/music/c6017d8a-2c37-4d51-a1c3-9246cc7ebc25?api_key=YOUR_API_KEY',
        description: 'Music artist artwork by MusicBrainz ID.',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'unknown',
    commercialUse: 'unclear',
    dataLicense: 'Fanart.tv terms — user-contributed art',
    freeTier: 'Free personal API key',
    rateLimit: 'Unpublished',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'reachability',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 0,
    sample: {
      name: 'movieposter',
      id: '75035',
      url: 'https://assets.fanart.tv/fanart/movies/550/movieposter/fight-club-sample.jpg',
    },
    shapeChanges: [],
  }),
  build({
    slug: 'tvdb',
    name: 'TVDB',
    emoji: '📺',
    tagline: 'TV series, episode and artwork metadata.',
    description:
      'TheTVDB v4 API covers series search, seasons, episodes, people and artwork references. Free personal API key at thetvdb.com. Bearer token auth; login endpoint exchanges key + pin for a short-lived JWT.',
    category: 'media',
    docsUrl: 'https://thetvdb.com/api-information',
    baseUrl: 'https://api4.thetvdb.com/v4',
    sampleEndpoint: '/languages',
    endpoints: [
      {
        method: 'GET',
        path: '/languages',
        description: 'Supported language codes for localized metadata.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/series/39340',
        description: 'Series record by TVDB ID (example: Breaking Bad).',
      },
      {
        method: 'GET',
        path: '/search?query=breaking%20bad',
        description: 'Full-text series search.',
      },
      {
        method: 'GET',
        path: '/series/39340/episodes/default',
        description: 'Default-ordered episode list for a series.',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'unknown',
    commercialUse: 'unclear',
    dataLicense: 'TVDB terms — user-contributed data',
    freeTier: 'Free personal API key',
    rateLimit: 'Unpublished',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'reachability',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 0,
    sample: {
      data: [{ id: 'eng', name: 'English', nativeName: 'English' }],
      status: 'success',
    },
    shapeChanges: [],
  }),
  build({
    slug: 'lastfm',
    name: 'Last.fm',
    emoji: '🎵',
    tagline: 'Music metadata and scrobbling from listener data.',
    description:
      'Last.fm API returns artist, album and track metadata plus similar-artist graphs built from scrobble data. Free API key after signup at last.fm/api. All calls require api_key in the query string; attribution to Last.fm required.',
    category: 'media',
    docsUrl: 'https://www.last.fm/api',
    baseUrl: 'https://ws.audioscrobbler.com/2.0',
    sampleEndpoint: '/?method=artist.search&artist=cher&api_key=YOUR_API_KEY&format=json',
    endpoints: [
      {
        method: 'GET',
        path: '/?method=artist.search&artist=cher&api_key=YOUR_API_KEY&format=json',
        description: 'Search artists by name.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/?method=artist.getinfo&artist=Cher&api_key=YOUR_API_KEY&format=json',
        description: 'Artist biography, tags and play counts.',
      },
      {
        method: 'GET',
        path: '/?method=artist.getSimilar&artist=Cher&api_key=YOUR_API_KEY&format=json',
        description: 'Similar artists from listener data.',
      },
      {
        method: 'GET',
        path: '/?method=artist.getTopTracks&artist=Cher&api_key=YOUR_API_KEY&format=json',
        description: 'Most popular tracks for an artist.',
      },
      {
        method: 'GET',
        path: '/?method=chart.getTopArtists&api_key=YOUR_API_KEY&format=json',
        description: 'Global top-artists chart.',
      },
      {
        method: 'GET',
        path: '/?method=tag.getTopTracks&tag=rock&api_key=YOUR_API_KEY&format=json',
        description: 'Top tracks for a genre tag.',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'unknown',
    commercialUse: 'unclear',
    dataLicense: 'Last.fm terms — attribution required',
    freeTier: 'Free personal API key',
    rateLimit: 'Unpublished',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'reachability',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 0,
    sample: {
      results: {
        artistmatches: {
          artist: [{ name: 'Cher', listeners: '1234567', url: 'https://www.last.fm/music/Cher' }],
        },
      },
    },
    shapeChanges: [],
  }),
  build({
    slug: 'trakt',
    name: 'Trakt',
    emoji: '📺',
    tagline: 'Watch history, ratings and streaming availability for movies and TV.',
    description:
      'Trakt.tv syncs what you watch across devices and exposes a JSON API for search, calendars, recommendations and streaming links. Free API key after OAuth app registration at trakt.tv/oauth/applications. Send Trakt-Api-Key and Trakt-Api-Version headers on every request.',
    category: 'media',
    docsUrl: 'https://trakt.docs.apiary.io/',
    baseUrl: 'https://api.trakt.tv',
    sampleEndpoint: '/movies/trending?extended=full',
    endpoints: [
      {
        method: 'GET',
        path: '/movies/trending?extended=full',
        description: 'Trending movies with full metadata.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/search/movie?query=fight+club',
        description: 'Search movies and shows by title.',
      },
      {
        method: 'GET',
        path: '/shows/tt0903747?extended=full',
        description: 'Show details by IMDb ID (Breaking Bad example).',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'unknown',
    commercialUse: 'unclear',
    dataLicense: 'Trakt terms — user-contributed data',
    freeTier: 'Free OAuth application',
    rateLimit: '1,000 req every 5 min documented',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'reachability',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 0,
    sample: {
      watchers: 12345,
      movie: { title: 'Fight Club', year: 1999, ids: { trakt: 1, imdb: 'tt0137523', tmdb: 550 } },
    },
    shapeChanges: [],
  }),
  build({
    slug: 'imdb-api',
    name: 'IMDb-API',
    emoji: '🎬',
    tagline: 'Unofficial IMDb metadata wrapper with a free tier.',
    description:
      'imdb-api.com is a third-party JSON wrapper over IMDb titles, cast, ratings and images — not affiliated with Amazon/IMDb. Free RapidAPI-style key after signup; distinct from OMDb and from our keyless IMDbOT scraper. Check terms before commercial use.',
    category: 'media',
    docsUrl: 'https://imdb-api.com/',
    baseUrl: 'https://imdb-api.com/en/API',
    sampleEndpoint: '/SearchMovie/knight&apikey=YOUR_API_KEY',
    endpoints: [
      {
        method: 'GET',
        path: '/SearchMovie/knight&apikey=YOUR_API_KEY',
        description: 'Search movies by keyword.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/Title/kw0468569&apikey=YOUR_API_KEY',
        description: 'Full title record by IMDb ID.',
      },
      {
        method: 'GET',
        path: '/Top250Movies/kw0468569&apikey=YOUR_API_KEY',
        description: 'IMDb Top 250 list.',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'unknown',
    commercialUse: 'no',
    dataLicense: 'Third-party scrape — not official IMDb',
    freeTier: 'Free tier with daily cap',
    rateLimit: 'Unpublished',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'reachability',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 0,
    sample: {
      searchType: 'Movie',
      results: [{ id: 'tt0468569', title: 'The Dark Knight', description: 'When the menace known as the Joker...' }],
    },
    shapeChanges: [],
  }),
  build({
    slug: 'simkl',
    name: 'Simkl',
    emoji: '📺',
    tagline: 'Trending movies, TV and anime with cross-IDs.',
    description:
      'Simkl tracks watch history and publishes read-only JSON for trending titles, ratings and cross-refs to IMDb, TMDb and TVDB. Trending and lookup routes work without a key; search and user routes need a client_id from simkl.com/settings/developer.',
    category: 'media',
    docsUrl: 'https://simkl.docs.apiary.io/',
    baseUrl: 'https://api.simkl.com',
    sampleEndpoint: '/tv/trending',
    endpoints: [
      {
        method: 'GET',
        path: '/tv/trending',
        description: 'TV series trending this week.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/movies/trending',
        description: 'Movies trending on Simkl right now.',
      },
      {
        method: 'GET',
        path: '/anime/trending',
        description: 'Anime trending across the community.',
      },
      {
        method: 'GET',
        path: '/movies/54114',
        description: 'Movie details by Simkl ID (Harry Potter example).',
      },
      {
        method: 'GET',
        path: '/search/movie?q=matrix',
        description: 'Search movies by title — requires client_id query param.',
      },
    ],
    auth: 'none',
    https: true,
    cors: 'unknown',
    commercialUse: 'unclear',
    dataLicense: 'Simkl terms — user-contributed data',
    freeTier: 'Free read routes; client_id for search',
    rateLimit: '1 req/s documented',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'endpoint',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 1200,
    sample: [
      {
        title: 'Silo',
        ids: { simkl_id: 1648964, slug: 'silo' },
        ratings: { imdb: { rating: 8.1, votes: 217211 } },
        network: 'Apple TV',
      },
    ],
    shapeChanges: [],
  }),
  build({
    slug: 'watchmode',
    name: 'Watchmode',
    emoji: '📡',
    tagline: 'Where to stream movies and shows by region.',
    description:
      'Watchmode maps titles to Netflix, Prime, Disney+ and dozens of other services by country. Free tier after signup at watchmode.com — 1,000 requests/month. Complements TMDb watch/providers with a dedicated streaming-availability index.',
    category: 'media',
    docsUrl: 'https://api.watchmode.com/docs/',
    baseUrl: 'https://api.watchmode.com/v1',
    sampleEndpoint: '/sources/?apiKey=YOUR_API_KEY',
    endpoints: [
      {
        method: 'GET',
        path: '/sources/?apiKey=YOUR_API_KEY',
        description: 'All streaming sources Watchmode tracks.',
        monitored: true,
      },
      {
        method: 'GET',
        path: '/search/?apiKey=YOUR_API_KEY&search_field=name&search_value=breaking%20bad',
        description: 'Search titles by name.',
      },
      {
        method: 'GET',
        path: '/title/345534/details/?apiKey=YOUR_API_KEY',
        description: 'Title metadata by Watchmode ID.',
      },
      {
        method: 'GET',
        path: '/title/345534/sources/?apiKey=YOUR_API_KEY',
        description: 'Streaming sources for a title by region.',
      },
      {
        method: 'GET',
        path: '/title/tt0903747/details/?apiKey=YOUR_API_KEY',
        description: 'Lookup by IMDb ID.',
      },
    ],
    auth: 'apiKey',
    https: true,
    cors: 'unknown',
    commercialUse: 'unclear',
    dataLicense: 'Watchmode terms',
    freeTier: 'Free — 1,000 req/month',
    rateLimit: '1,000 req/month (free tier)',
    requiresCard: false,
    status: 'unmonitored',
    checkTier: 'reachability',
    addedAt: '2026-07-05',
    lastCheckedMin: 0,
    baseLatency: 0,
    sample: {
      id: 345534,
      title: 'Breaking Bad',
      type: 'tv_series',
      imdb_id: 'tt0903747',
    },
    shapeChanges: [],
  }),
  // 669 verified imports from public directories (public-apis, free-apis.github.io, apimap, freepublicapis, etc.).
  ...importedSpecs.map(build),
]

// --- Derived helpers --------------------------------------------------------

export const bySlug = new Map(apis.map((a) => [a.slug, a]))
export const categoryBySlug = new Map(categories.map((c) => [c.slug, c]))

export function apisInCategory(slug: string): ApiEntry[] {
  return apis.filter((a) => a.category === slug)
}

export function liveApis(): ApiEntry[] {
  return apis.filter((a) => a.status !== 'dead')
}

export function deadApis(): ApiEntry[] {
  return apis.filter((a) => a.status === 'dead')
}

export interface ChangeEvent {
  slug: string
  name: string
  emoji: string
  category: string
  date: string
  summary: string
}

/** Every response-shape change across the catalog, newest first — the schema-drift changelog. */
export function allShapeChanges(): ChangeEvent[] {
  return apis
    .flatMap((a) => a.shapeChanges.map((s) => ({ slug: a.slug, name: a.name, emoji: a.emoji, category: a.category, date: s.date, summary: s.summary })))
    .sort((x, y) => y.date.localeCompare(x.date))
}

export function uptimePct(a: ApiEntry, days = 90): string {
  const series = a.uptime90
  if (!series?.length) return '—'
  const window = series.slice(-days).filter((v) => v >= 0)
  if (!window.length) return '—'
  const avg = (window.reduce((x, y) => x + y, 0) / window.length) * 100
  return avg >= 99.95 ? '100' : avg.toFixed(avg >= 99 ? 2 : 1)
}

/** Hero "live signals" feed — deterministic sample of recent check events (→ real checker output later). */
export interface Signal {
  slug: string
  name: string
  emoji: string
  kind: 'ok' | 'warn' | 'fail'
  detail: string
  ago: string
}

export const recentSignals: Signal[] = [
  { slug: 'ipify', name: 'ipify', emoji: '🔌', kind: 'ok', detail: '48 ms', ago: '12s' },
  { slug: 'open-meteo', name: 'Open-Meteo', emoji: '🌤', kind: 'ok', detail: '96 ms', ago: '47s' },
  { slug: 'coingecko', name: 'CoinGecko', emoji: '🦎', kind: 'warn', detail: 'HTTP 429', ago: '2m' },
  { slug: 'open-notify', name: 'Open Notify', emoji: '🛰', kind: 'fail', detail: 'timeout', ago: '3m' },
  { slug: 'wikipedia-rest', name: 'Wikipedia REST', emoji: '📰', kind: 'ok', detail: '91 ms', ago: '5m' },
  { slug: 'frankfurter', name: 'Frankfurter', emoji: '💱', kind: 'ok', detail: '84 ms', ago: '7m' },
  { slug: 'pokeapi', name: 'PokéAPI', emoji: '⚡', kind: 'ok', detail: '71 ms', ago: '8m' },
  { slug: 'dog-ceo', name: 'Dog CEO', emoji: '🐶', kind: 'ok', detail: '139 ms', ago: '9m' },
  { slug: 'nominatim', name: 'Nominatim (OSM)', emoji: '📍', kind: 'ok', detail: '241 ms', ago: '11m' },
]

export interface StatusChange {
  slug: string
  name: string
  emoji: string
  from: LifecycleStatus
  to: LifecycleStatus
  when: string
}

export const statusChanges: StatusChange[] = [
  { slug: 'open-notify', name: 'Open Notify', emoji: '🛰', from: 'degraded', to: 'dying', when: '6d' },
  { slug: 'coingecko', name: 'CoinGecko', emoji: '🦎', from: 'healthy', to: 'degraded', when: '14d' },
  { slug: 'chartlyrics', name: 'ChartLyrics', emoji: '🎵', from: 'dying', to: 'dead', when: 'Jun 2' },
]

export const globalStats = (() => {
  const live = liveApis()
  const checks24h = live.length * 96 // */15 cron × 45-batch → ~96 windows/day at catalog scale
  const medianLatency = (() => {
    const p50s = live.filter((a) => a.p50 > 0).map((a) => a.p50).sort((x, y) => x - y)
    return p50s[Math.floor(p50s.length / 2)] ?? 0
  })()
  const diedThisMonth = deadApis().length
  return {
    tracked: apis.length,
    checks24h,
    medianLatency,
    diedThisMonth,
  }
})()
